user_auth/forms.py
from cProfile import label
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import Subscription

class NewUser(UserCreationForm):
    email = forms.EmailField(required=True)

    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'username','email', 'password1', 'password2']
    
    def save(self, commit=True):
        user = super(NewUser, self).save(commit=False)
        user.email = self.cleaned_data['email']
        if commit:
            user.save()
        return user

class SubscriptionForm(forms.Form):
    subscription_choices = [
        ('Free_Plan','Free plan'),
        ('Student_plan', 'Student Plan'),
        ('Organisation_Plan', 'Organisation Plan')
    ]
    subscription_plan = forms.CharField(
        label="Choose a Subscription Plan",
        widget=forms.RadioSelect(choices=subscription_choices
        )
    )
    username = forms.CharField(max_length=50)
    

user_auth/views.py
from django.shortcuts import get_object_or_404, render, redirect
from django.contrib import messages
from django.contrib.auth.models import User

from .forms import NewUser, SubscriptionForm
from .models import Subscription

def home(request):
    return render(request, 'home.html', {})

def signup(request):
    if request.method =='POST':
        form = NewUser(request.POST)
        if form.is_valid():
            username = request.POST.get("username")
            print(username)
            form.save()
            messages.success(request, 'Registration Successful')
            return redirect(f"/subscription/{username}", )
        messages.error(request, "Invalid Information")
    
    form = NewUser()
    context = {
        'form':form
    }
    return render(request, 'registration/signup.html', context)

def subscription(request, id=id):
    username = id
    if request.method == "POST":
        form = SubscriptionForm(request.POST)
        # print(form)
        # form.subscription_plan = request.POST.get("subscription_plan")
        # print(form.subscription_plan)
        # print(form.cleaned_data)
        if form.is_valid():
            form_user = form.cleaned_data['username']
            form_subs = form.cleaned_data['subscription_plan']
            form_data = Subscription(subscription_plan = form_subs, username = username)
            form_data.save()
            return redirect("/login")

    form = Subscription()
    context = {
        'username' : username,
        'subscription_plan': form.subscription_plan
    }
    return render(request, "subscription.html", context)

def dashboard(request, id=id):
    user = get_object_or_404(User, username=id)
    # user = User.objects.get(username=username)

    context ={
        "first_name": user.first_name
    }
    return render(request, 'dashboard.html', context)

def plan_info(plan):
    plan_information = []
    if plan == "Student_Plan":
        plan_information.append('Student Plan')
        plan_information.append(10)
        return plan_information
    elif plan == "Organisation_Plan":
        plan_information.append('Organisation Plan')
        plan_information.append(25)
        return plan_information
    else:
        plan_information.append('Free Plan')
        plan_information.append(5)
        return plan_information

def account(request, id=id):
    user = User.objects.get(username=id)
    storage = Subscription.objects.get(username=id)
    plan = plan_info(storage.subscription_plan)
    storage_used = storage.storage_used
    # print(plan)
    selected_plan = plan[0]
    allocated_storage = plan[1]
    remaining_storage = allocated_storage - storage_used
    # print(f'--------------{remaining_storage}')

    context = {
        'user' : user,
        'allocated_storage' : allocated_storage,
        'selected_plan' : selected_plan,
        'remaining_storage' : remaining_storage
    }
    return render(request, 'account.html', context)

user_auth/templates/account.html
{% extends "layout.html" %}
{% block style %}
<style>
  /* Add a black background color to the top navigation */
  .topnav {
    background-color: white;
    overflow: hidden;
  }

  /* Style the links inside the navigation bar */
  .topnav a {
    float: left;
    display: block;
    color: #ffffff;
    text-align: center;
    padding: 14px 16px;
    text-decoration: none;
    font-size: 17px;
  }

  /* Add an active class to highlight the current page */
  .topnav a.active {
    background-color: #04AA6D;
    color: white;
  }

  .topnav a.right {
    background-color: #04AA6D;
    color: rgb(255, 255, 255);
    float: right;
  }

  /* Hide the link that should open and close the topnav on small screens */
  .topnav .icon {
    display: none;
  }
</style>
{% endblock style %}

{% block content %}
<div class="topnav" id="myTopnav">
  <a href="{% url 'home'%}" class="active">Home</a>
  <a href="/dashboard/{{user.username}}" class="active">Dashboard</a>
  <a href="../account/{{user.username}}" class="active">Account</a>

  <a href="{% url 'logout' %}" class="right">Logout</a>

</div>
<br>

<div>
  <h2>
    <p class="text-center ">Welcome {{ user.first_name|default:'Guest'}}{{user.last_name}}, to your account</p>
  </h2>


  <h3 class="text-secondary">Username : {{ user.username }}</h3>
  <h3 class="text-secondary">Email : {{ user.email }}</h3>
  <hr><br>
  <h3 class="text-secondary"> More Information:</h3>
  <h5 class="text-seconday"> Current Plan: {{ selected_plan }}</p>
  <h5 class="text-secondary">Allocated Space: {{ allocated_storage }} GB</h5>
  <h5 class="text-secondary">Free Space: {{ remaining_storage }} GB</h5>
</div>
{% endblock content %}

user_auth/templates/dashboard.html
{% extends "layout.html" %}
{% block style %}
<style>
	/* Add a black background color to the top navigation */
.topnav {
  background-color: white;
  overflow: hidden;
}

/* Style the links inside the navigation bar */
.topnav a {
  float: left;
  display: block;
  color: #ffffff;
  text-align: center;
  padding: 14px 16px;
  text-decoration: none;
  font-size: 17px;
}

/* Add an active class to highlight the current page */
.topnav a.active {
  background-color: #04AA6D;
  color: white;
}

.topnav a.right{
  background-color: #04AA6D;
  color: rgb(255, 255, 255);
  float: right;
}

  /* Hide the link that should open and close the topnav on small screens */
  .topnav .icon {
    display: none;
  }
</style>
{% endblock style %}

{% block content %}
	<div class="topnav" id="myTopnav">
		<a href="{% url 'home'%}" class="active">Home</a>
		<a href="../dashboard/{{user.username}}" class="active">Dashboard</a>
		<a href="/account/{{user.username}}" class="active">Account</a>
		<a href="..{% url 'logout' %}" class="right">Logout</a>
	
	</div>
	<br>


	<h2><p class="text-center ">Welcome, {{ user.first_name|default:'Guest' }} to your Dashboard</p></h2>
	<hr><br>
	
	<center>
		<div class="border border-dark p-3 mb-3" id="mydiv1" >
			<table border="0">
				<tr>
					<th>Your Uploads</th>
				</tr>
				
				<tr>
					{%if list %}
						
						<td>{{ list }}
						<a>{{ name }}</a>
					{% else %}
						<td> Upload files here</td>
					{% endif %}	
					<br>
					</td>
				</tr>
			</table>
		</div>
	</center>
	<br><hr style="width:50%;text-align:center;">
	<div class="border border-dark p-3 mb-3">
          <center>
			<button onclick="showUploadDiv('mydiv')" class="btn btn-outline-info">
          		Upload
          	</button>
          	<button onclick="showDownloadDiv('mydiv1')" class="btn btn-outline-info">
          		Download
          	</button>
          	</center>
        
        </div>


	    <div class="border border-dark p-3 mb-3" id="mydiv" style="display: none">
			<form action="/upload" method="POST" enctype="multipart/form-data">
				<div class="form-group">
					<label>Select File</label>
					<div class="custom-file">
						<input oninput="filesize(this);" type="file" class="custom-file-input" name="file" id="file">
						<label class="custom-file-label" for="file">No File Selected</label>
					</div>
				</div>

				<button type="submit" class="btn btn-outline-info">Upload File</button>
			</form>
		</div>


{% endblock content %}

{% block script %}

<script>
function showUploadDiv(ele) 
{
var srcElement = document.getElementById(ele);
	if (srcElement != null) 
	{
		if (srcElement.style.display == "block") 
		{
			srcElement.style.display = 'none';
		}
		else 
		{
			srcElement.style.display = 'block';
		}
		return false;
	}
}

function showDownloadDiv(ele) 
{
var srcElement = document.getElementById(ele);
	if (srcElement != null) 
	{
		if (srcElement.style.display == "block") 
		{
			srcElement.style.display = 'none';
		}
		else 
		{
			srcElement.style.display = 'block';
		}
		return false;
	}
}

$(".custom-file-input").on("change", function() {
  var fileName = $(this).val().split("\\").pop();
  $(this).siblings(".custom-file-label").addClass("selected").html(fileName);
});


function filesize(elem)
{
	document.cookie = `filesize=${elem.files[0].size}`;
}


</script>


{% endblock %}

user_auth/templates/subscription.html
{% extends "layout.html" %}
{% block style %}

<style>
    input[type=text],
    input[type=password],
    input[type=email] {
        width: 90%;
        padding: 15px;
        margin: 5px 0 22px 0;
        display: inline-block;
        border: none;
        background: #f1f1f1;
    }

    input[type=text]:focus,
    input[type=password]:focus {
        background-color: #ddd;
        outline: none;
    }

    hr {
        border: 1px solid #f1f1f1;
        margin-bottom: 25px;
    }

    /* Set a style for all buttons */
    button {
        background-color: #04AA6D;
        color: white;
        padding: 14px 20px;
        margin: 8px 0;
        border: none;
        cursor: pointer;
        width: 100%;
        opacity: 0.9;
    }

    button:hover {
        opacity: 1;
    }

    /* Extra styles for the cancel button */
    .content-section {
        width: 40%;

        position: relative;
        top: 50px;
        bottom: 0;
        left: 0;
        right: 0;

        margin: auto;
    }

    .text-muted {
        position: relative;
        top: 50px;
        left: 40%;

    }

    .signupbtn {
        float: left;
        width: 50%;
    }

    /* Add padding to container elements */
    .container {
        padding: 16px;
    }

    /* Clear floats */
    .clearfix::after {
        content: "";
        clear: both;
        display: table;
    }

    /* Change styles for cancel button and signup button on extra small screens */
    @media screen and (max-width: 300px) {

        .cancelbtn,
        .signupbtn {
            width: 100%;
        }
    }

    /* Add a black background color to the top navigation */
    .topnav {
        background-color: white;
        overflow: hidden;
    }

    /* Style the links inside the navigation bar */
    .topnav a {
        float: left;
        display: block;
        color: #ffffff;
        text-align: center;
        padding: 14px 16px;
        text-decoration: none;
        font-size: 17px;
    }

    /* Add an active class to highlight the current page */
    .topnav a.active {
        background-color: #04AA6D;
        color: white;
    }

    .topnav a.right {
        background-color: #04AA6D;
        color: rgb(255, 255, 255);
        float: right;
    }

    /* Hide the link that should open and close the topnav on small screens */
    .topnav .icon {
        display: none;
    }
</style>
{%endblock style%}

{% block content %}

<div class="topnav" id="myTopnav">
    <a href="{%url 'home'%}" class="active">Home</a>
    <a href="{%url 'login'%}" class="active">Dashboard</a>
    <a href="{%url 'login'%}" class="active">Account</a>
    <a href="{%url 'signup'%}" class="right">Register</a>

</div>
<br>
<div class="content-section">
    <h2>
        <p class="text-center ">Hi! {{ user.first_name}}{{user.last_name}},</p>
    </h2>
    <form method="POST">
        {%csrf_token%}
        <tr>
            <th><label><h2>Choose a Subscription Plan:</h2></label></th>
            <td>
                <ul class="errorlist">
                    <li>This field is required.</li>
                </ul>
                <div id="id_subscription_plan">
                    <div>
                        <label for="id_subscription_plan_0"><input type="radio" name="subscription_plan"
                                value="Free_Plan" required id="id_subscription_plan_0">
                                <strong>Free Plan</strong></label>
                        <p> &emsp; -- Free plan is basically a trial plan for new users</p>
                        <p> &emsp; -- You get 5GB of total cloud space on going with the free plan</p>


                    </div>
                    <div>
                        <label for="id_subscription_plan_1"><input type="radio" name="subscription_plan"
                                value="Student_Plan" required id="id_subscription_plan_1">
                            <strong>Student Plan</strong></label>
                        <p> &emsp; -- Student plan is for students where student can store all their course work, </p>
                        <p> &emsp; i.e. notes, assignments etc. </p>
                        <p> &emsp; -- Get 10Gb of cloud storage on this student plan at 5$</p>


                    </div>
                    <div>
                        <label for="id_subscription_plan_2"><input type="radio" name="subscription_plan"
                                value="Organisation_Plan" required id="id_subscription_plan_2">
                            <strong>Organisation Plan</strong></label>
                        <p> &emsp; -- Organisation plan is for startups or small companies who want to store all their
                        <p> &emsp; information like important documents, official work etc. on cloud </p>
                        <p> &emsp; -- Get 25Gb of cloud storage on this student plan at 15$</p>
                        <p> &emsp; -- For organisation we can also provide custom storage space</p>

                    </div>
                </div>


            </td>
        </tr>
        <button type="submit" class="button"> Sign up </button>
</div>
</form>
</div>

{% endblock content%}